corda/quasar

build.gradle, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/JavaAgent.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/QuasarInstrumentor.java, quasar-core/src/test/java/co/paralleluniverse/fibers/instrument/ClassLoaderExclusionTest.java
Modify Quasar's Java agent so that we can exclude all classes belonging to any classloader that matches one of our patterns.
=> CORDA-3228: Implement a filter to exclude entire classloaders.

build.gradle
Remove the Maven classifier from:
> co.paralleluniverse:quasar-core:jdk8:0.7.13_r3-SNAPSHOT
This allows us to override the Quasar agent cleanly with:
> co.paralleluniverse:quasar-core:0.8.0_r3
for our Java 11 builds.
=> ENT-4967: Declare the JDK8 quasar-core agent as the main artifact for 0.7.x.

quasar-core/src/main/java/co/paralleluniverse/common/util/ExtendedStackTrace.java, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/MethodOverloadTest.kt
This fix helps Quasar identify the correct method overload when running under OpenJDK.
Up until now, it has relied on the line number from a stack trace falling between the start and end line numbers for a method. I've found that it is possible for the compiler to pull a constant out of the method and give it a fake line number beyond the end of the file. That breaks Quasars search for the correct method overload. An example can be seen in CORDA-3667.
This fix makes Quasar prefer a method where it sees an exact match to the line number in the stack trace and falls back on existing behaviour when that is not the case.
I've introduced variables for the line number and method name read from the stack trace object (`este`). I can reverse this for a simpler diff if requested.
=> CORDA-3667: Add support for method overloads in quasar

quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/JavaAgent.java
Access the `Classes` class before we hook into the JVM, so static initialisation completes before Quasar starts work.
One concern is the optimiser removing unused code. To avoid that, I've written a debug log message while calling a static method and accessing a static field on the `Classes` class.
An alternative fix for https://github.com/corda/quasar/pull/10
=> CORDA-3666: Access the Classes class before we hook into the JVM

gradle.properties, quasar-core/src/main/java/co/paralleluniverse/common/util/Debug.java, quasar-core/src/test/java/co/paralleluniverse/fibers/instrument/ReflectionInvokeTest.java
Gradle uses the `quasar-core` build artifact to run the tests, which means that the Gradle daemon will crash if this artifact is subsequently modified on disk. It's probably safer _not_ to use a Gradle daemon at all for building Quasar.
Also, Quasar by default will refuse to instrument classes from the `co.paralleluniverse.fibers.instrument` package. This is fine _except_ for running instrumentation unit tests. Quasar tries to spot when it's being unit tested, but the logic has a spelling mistake! (Either that, or Gradle 4.x _had_ a spelling mistake which Gradle 5.x has now fixed.). Update this `Debug` logic so that `ReflectionInvokeTest` can be executed correctly _in isolation_ from within IntelliJ.
=> NOTICK: Fix subtle build errors caused by Gradle daemon.

gradle.properties, quasar-core/src/main/java/co/paralleluniverse/common/util/Debug.java, quasar-core/src/test/java/co/paralleluniverse/fibers/instrument/ReflectionInvokeTest.java
Gradle uses the `quasar-core` build artifact to run the tests, which means that the Gradle daemon will crash if this artifact is subsequently modified on disk. It's probably safer _not_ to use a Gradle daemon at all for building Quasar.
Also, Quasar by default will refuse to instrument classes from the `co.paralleluniverse.fibers.instrument` package. This is fine _except_ for running instrumentation unit tests. Quasar tries to spot when it's being unit tested, but the logic has a spelling mistake! (Either that, or Gradle 4.x _had_ a spelling mistake which Gradle 5.x has now fixed.). Update this `Debug` logic so that `ReflectionInvokeTest` can be executed correctly _in isolation_ from within IntelliJ.
=> NOTICK: Fix subtle build errors caused by Gradle daemon

build.gradle
Create a lazy `Provider` to evaluate the shaded jar's `file:` URI, and then assign it to a project property so that bnd can invoke it as a macro. This avoids using deprecated Gradle behaviour that will be removed in Gradle 7.0, but should otherwise have no noticeable effect.
Also evaluate `project.version` lazily, for good measure.
=> CORDA-4032: Evaluate Gradle provider lazily as a bnd macro.

build.gradle, gradle.properties, quasar-core/src/main/agent/module-info.java, quasar-core/src/main/bundle/module-info.java, quasar-core/src/main/java/module-info.java
Generate `module-info` files for each Quasar OSGi artifact so that they can participate properly in a modular system.
These replace the unsuitable `module-info` file from the original `quasar-core` artifact.
=> CORDA-4064: Add module-info for OSGi artifacts.

build.gradle, gradle.properties
Upgrade Bnd 5.1.2 -> 5.2.0.
Bnd 5.2 adds the new Java modules to the `Import-Package` header, so now we need to extract the package names which are not `java.*` before validating the bundles.
=> NOTICK: Upgrade to Bnd 5.2.0.

.ci/dev/Jenkinsfile, build.gradle, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/SimpleSuspendableClassifier.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/SuspendablesScanner.java
Move Quasar's built-in lists of suspendables into the instrumentation agent jar, so that they are found immediately even within an OSGi framework.
Also remove Gradle task which generates duplicate suspendables inside `quasar-core`, and fix some compiler warnings.
=> CORE-613: Migrate META-INF/suspendable* files to OSGi agent.

build.gradle
Provide the `scanAndInstrument` operation with its own output directory. This prevents the `META-INF/suspendable-supers` file from being clobbered accidentally by the `processResources` task.
**NOTE: This generated file will conflict with any `META-INF/suspendable-supers` file subsequently added to any project's `src/main/resources` directory.**
=> CORE-613: Fix generation of META-INF/suspendable-supers for Quasar itself.

quasar-core/src/main/java/co/paralleluniverse/fibers/DefaultFiberScheduler.java, quasar-core/src/main/java/co/paralleluniverse/fibers/FiberExecutorScheduler.java, quasar-core/src/main/java/co/paralleluniverse/fibers/FiberScheduler.java, quasar-core/src/main/java/co/paralleluniverse/fibers/FiberUtil.java, quasar-core/src/main/java/co/paralleluniverse/fibers/SchedulerLocal.java
`DefaultFiberScheduler` is now an OSGi bundle and not part of the Quasar agent. Therefore it should not automatically register a JMX bean during its `<clinit>` method because this prevents the bundle from being reloaded into the OSGi framework.
Also fix another batch of simple compiler warnings, mostly related to Java generics.
=> CORE-902: Prevent DefaultFiberScheduler from registering JMX bean by default.

build.gradle, quasar-kotlin/build.gradle, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/OOTest.kt
We need to enable default methods for Kotlin interfaces, but are currently blocked by a Kotlin compiler bug.
See [KT-46253](https://youtrack.jetbrains.com/issue/KT-46253).
Also tidy up a few Gradle / Kotlin warnings, and switch to using Gradle's toolchains for selecting JDK11.
=> NOTICK: Document how Kotlin default interface methods are broken.

build.gradle, gradle.properties, quasar-kotlin/build.gradle, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/OOTest.kt
Add test-cases for Kotlin interface methods with `@JvmDefault`. These are for documentation purposes, since the Kotlin compiler itself generates incorrect byte-code for them.
See [KT-46253](https://youtrack.jetbrains.com/issue/KT-46253).
Ensure we test `quasar-kotlin` against the same Kotlin version as Corda 4.x uses.
Also resolve a few Kotlin / Gradle warnings.
=> NOTICK: Add test cases for Kotlin with @JvmDefault.

build.gradle
- Set the disabled `Jar` task's classifier to "ignore", to differentiate it from the `ShadowJar` artifact.
- Remove deprecated "maven" plugin.
- Disable unused Gradle metadata.
- Remove `jcenter()` repository.
=> NOTICK: Fix Quasar publication with Gradle 6.8.3.

build.gradle
- Remove deprecated `maven` plugin.
- Remove deprecated `jcenter()` repository.
- Add 'ignore' classifier to disabled `jar` task to differentiate it from shadowJar task artifact.
=> NOTICK: Backport publication changes from release/0.8 branch.

build.gradle, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/SimpleSuspendableClassifier.java, quasar-core/src/main/java/co/paralleluniverse/io/serialization/kryo/ExternalizableKryoSerializer.java, quasar-kotlin/build.gradle, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/actors/PingPongWithDefer.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/FiberAsyncTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/FiberKotlinTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/StaticPropertiesTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/AbstractTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/FunTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/MethodOverloadTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/OOTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/SyntheticAbstractTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/SyntheticTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/stdlib/StdDelegates.kt
- Remove unused `static final` field from `ExternalizableKryoSerializer`.
- Fix some spelling errors and compiler warnings.
- Remove some more Gradle cruft.
- Tidy up more imports.
=> NOTICK: Backport cruft removal from release/0.8 branch.

build.gradle, quasar-core/src/main/agent/module-info.java, quasar-core/src/main/bundle/module-info.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/SimpleSuspendableClassifier.java, quasar-core/src/main/java/co/paralleluniverse/io/serialization/kryo/ExternalizableKryoSerializer.java, quasar-core/src/main/java/module-info.java, quasar-kotlin/build.gradle, quasar-kotlin/src/AnnotationTest/kotlin/co/paralleluniverse/kotlin/fibers/AnnotationTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/StaticPropertiesTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/AbstractTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/FunTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/MethodOverloadTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/OOTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/SyntheticAbstractTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/SyntheticTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/_1_4_x/BreakContinueTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/_1_4_x/CallableReference.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/_1_4_x/LambdaTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/_1_4_x/NameAndPositionalArgumentsTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/_1_4_x/SAMTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/stdlib/StdDelegates.kt
- The correct syntax for JPMS `opens` is "opens package to module".
- Kryo only has "automatic" module names, which cannot safely be used at runtime. Ensure they're only used for compiling.
- Remove unused `static final` field from `ExternalizableKryoSerializer`.
- Fix some spelling errors and compiler warnings.
- Remove some more Gradle cruft.
- Tidy up more imports.
=> NOTICK: Fix errors in JPMS descriptors.

quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/MethodDatabase.java
Quasar's "common super class" algorithm assumes that the byte code for a class's super classes is always readable via that class's own classloader. This is not necessarily true when that class belongs to an OSGi bundle within an OSGi framework, which requires that the classloader have a "bundle wiring" to the super class's package as well.
Quasar currently knows nothing about OSGi or bundle wirings, which means that its common super class algorithm can fail within an OSGi framework. However, we can reduce the likelihood of it failing by observing up front that the common super class of `java.lang.Object` and _anything_ **must** be `java.lang.Object`.
=> CORE-1519: Optimise common super class calculation when one class is java.lang.Object.

quasar-core/src/main/java/co/paralleluniverse/common/asm/ASMUtil.java, quasar-core/src/main/java/co/paralleluniverse/common/util/ExtendedStackTrace.java, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/MethodOverloadTest.kt
- Use an inline function to make MethodOverloadTest more robust
- Port fix to 0.8 branch
See https://github.com/corda/quasar/pull/9 for the 0.7 fix.
=> CORE-1790: Port method overload fix to 0.8

quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/MethodOverloadTest.kt
This makes the unit test work on both Java 8 and 11.
=> CORE-1790: Use an inline function to make MethodOverloadTest more robust

quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/DefaultSuspendableClassifier.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/JavaAgent.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/Retransform.java, quasar-osgi-tests/tests.bndrun
Remove strong `ClassLoader` references from `DefaultSuspendableClassifier`. This allows the instrumentor's
```java
WeakHashMap<ClassLoader, MethodDatabase>
```
instance to release unused classloaders as it is supposed to.
Also remove `Set<WeakReference<ClassLoader>>` _completely_ from `JavaAgent` as it does _not_ behave as a weak `Set<ClassLoader`, and is also unused anyway.
=> CORE-3417: Ensure Java agent can unload unused ClassLoaders.

build.gradle, quasar-core/src/main/agent/module-info.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/JavaAgent.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/MethodDatabase.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/OSGiClassLoader.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/function/BiFunction.java, quasar-core/src/main/java/co/paralleluniverse/fibers/osgi/ExtractSuperClasses.java
Create and execute the `ExtractSuperClasses` object via a lambda rather than using Java reflection. This removes Java reflection from normal operation entirely.
Also fix incremental build of OSGi Quasar's agent.
=> CORE-4077: Execute OSGi ExtractSuperClasses via a lambda.

gradle.properties, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/Classes.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/DefaultSuspendableClassifier.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/InstrumentClass.java, quasar-kotlin/build.gradle, quasar-kotlin/src/main/java/co/paralleluniverse/kotlin/KotlinClassifier.java, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/MethodOverloadTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/OOTest.kt, quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/lang/_1_4_x/CallableReference.kt
Kotlin 1.5+ began implementing lambdas using Java's bootstrap methods, and Kotlin 1.6.20 has ensured that lambdas are once again serializable by default. We can now consider using Quasar with Kotlin 1.6.20+.
Kotlin is also now generating a compiler warning for [KT-46253](https://youtrack.jetbrains.com/issue/KT-46253), so we can avoid this bug too by enabling
```
allWarningsAsErrors = true
```
=> CORE-4674: Instrument Kotlin 1.6.x lambdas correctly.

quasar-core/src/main/java/co/paralleluniverse/fibers/Stack.java
Apply existing fix from [Quasar#309](https://github.com/puniverse/quasar/issues/309).
=> ENT-6766: Fix ArrayOutOfBoundsException in Stack.popMethod.

quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/OSGiClassLoader.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/QuasarInstrumentor.java
Fix `OSGIClassLoader` function references never to be `null`. This avoids a NPE whenever there is no OSGi framework on the classpath.
=> CORE-4592: Fix NPE when OSGi framework not on classpath.

quasar-core/src/main/java/co/paralleluniverse/common/resource/ClassLoaderUtil.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/MethodDatabase.java, quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/SuspendablesScanner.java
Disabling caching forces Java to create a new `JarFile` for each `JarURLConnection`. This causes a quadratic performance penalty when instrumenting signed jars because each `JarFile` must validate the jar's signatures.
Revert to previous behaviour of using `URLConnection.defaultUseCaches` setting. (We appear to have inherited the original change from the original 0.8 code.)
=> CORE-4818: Do not disable caching when reading URLConnection.
